# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JJBBe70I+a+XXTF7kCOvBOEkPYzqwX98ibH10dX/iHAS6Uz/b/d2Sx3v/N0DoOiWW6u/a2G9UQBog8Qh2QUFRl9o3AfdXoohcdOBy9OAlma7ml3UM6kdCQMIanBIRpQ9hOcVFwqI7tB+BwYm5ukZIfsBob6NE93KOQKg1sFwslt8l99B1Lqvv1C4NrA11pyeAqiIUIUlI4i6JGlOZpBISbN5qpkY3EeeWSIrA9sIg9l0a+BEOvodusZ4wAf0g4MtFxduN6MHMQCNA9DNDozTFAXMMpwYS/TFGod51fnLPXyi3/tp50JM+SSx+Dw2lZnYnsz8Zh44BSfmOYIxNqXdnagtwBXj0BM2RFC85B6QXCoh2hX1cBnrc6MtoBI9aU36QLti/9DQJ84k6mHVcISXewHWBAAAy4NZ6GKyIEw51GiZLGcHKAKB474W3E7S0eYSSvFAZznXCRCnJWyxeYgQKEkQxshHid24t4JT/hA/2ZbPKH6uG19fAM4oe1888/lJO1C/1vg8K2Re3CUp8c3rjxfj/6IxYGvAYiSK0cqw/umClfY6w9HCt/P5OLt2o4l04yuawKrOml3dHNOpZr5ymf0Av8bXiRVt6zBZAyPSQtqQBGANHgZ/FZraiGJ2MfTnOstqyuYigw/AW9p2ku69+gHnVE5sYi7c+mr6nD9pgDY="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
