travis:
  secure:
    BINSTAR_TOKEN: CeEAB5kRUVzXfJ7aCJR82P01BPO4fRbLuUqfZ/uV9Gu+1HDI5M9b+y0YsHzD+724gTbi36R4Po3EPrGXSIlR/IwU6d7aXb1DQRzOxTN3IpCGjZY2PRdMWoh2XjPls77nl1/YtmRlrEad2rTgz4vKC4oZd4e2syQ8I3d0XwgFjktNhlNpb0zQdJmNNL2gEcmnKx9x/vOU4o5BaXmwt9fCHH/DEmT3jVCOclGD8Nile2azyrKczsx02JowhURERpRGwD82Fz6Ua1OcBCN5ssjou8aiqe0WE1FsBL4wL5QxcuDD03xntut5c2v94XgPsNoo05zIclCzwkVBOp3g1UUXLpEFJMP6mOGHltJxutQ2smCvIWQ/zZ+7/b+rPZDK5LOCJHbIwHlfjicI4gvO24yjqAmG+mZN4KYP21c/7VmajyPvl16UBe1deYtntx5FlgNt/FZlHC3BJ1Kb5dYgnptkGVIoQtSJLmLt9C3dtjkLzhD5g6D4jnx2PnHjRLjdyd8q4jIO1MmsxcaWcht2TZT8l5+4CxWDNqexooAW2wdJE54oZ3IErhX/Cc0N/9oFBrUMlDipqmWCsutzqPQLVlwaSAtgum2jtV2JaKwLsGVrfa1QxHupc1y/DX28+XexOR9yVw7QeLF1lApAgaLX2duxsOkG27Oy5R7n4+IeVlJi94k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
