travis:
  secure:
    BINSTAR_TOKEN: JJBBe70I+a+XXTF7kCOvBOEkPYzqwX98ibH10dX/iHAS6Uz/b/d2Sx3v/N0DoOiWW6u/a2G9UQBog8Qh2QUFRl9o3AfdXoohcdOBy9OAlma7ml3UM6kdCQMIanBIRpQ9hOcVFwqI7tB+BwYm5ukZIfsBob6NE93KOQKg1sFwslt8l99B1Lqvv1C4NrA11pyeAqiIUIUlI4i6JGlOZpBISbN5qpkY3EeeWSIrA9sIg9l0a+BEOvodusZ4wAf0g4MtFxduN6MHMQCNA9DNDozTFAXMMpwYS/TFGod51fnLPXyi3/tp50JM+SSx+Dw2lZnYnsz8Zh44BSfmOYIxNqXdnagtwBXj0BM2RFC85B6QXCoh2hX1cBnrc6MtoBI9aU36QLti/9DQJ84k6mHVcISXewHWBAAAy4NZ6GKyIEw51GiZLGcHKAKB474W3E7S0eYSSvFAZznXCRCnJWyxeYgQKEkQxshHid24t4JT/hA/2ZbPKH6uG19fAM4oe1888/lJO1C/1vg8K2Re3CUp8c3rjxfj/6IxYGvAYiSK0cqw/umClfY6w9HCt/P5OLt2o4l04yuawKrOml3dHNOpZr5ymf0Av8bXiRVt6zBZAyPSQtqQBGANHgZ/FZraiGJ2MfTnOstqyuYigw/AW9p2ku69+gHnVE5sYi7c+mr6nD9pgDY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
